name: Extract Blobs

on:
  workflow_dispatch:
    inputs:
      DEVICE_TREE_REPO:
        description: 'Device Tree Repository URL'
        required: true
        default: ''
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Repository Branch'
        required: true
        default: ''
      DEVICE_CODENAME:
        description: 'Device Codename'
        required: true
        default: ''
      DEVICE_VENDORNAME:
        description: 'Device Vendor Name'
        required: true
        default: ''
      USER_NAME:
        description: 'Name in Github Account'
        required: true
        default: 'bibi09456'
      USER_EMAIL:
        description: 'E-mail in Github Account'
        required: true
        default: '55490658+bibi09456@users.noreply.github.com'

jobs:
  build:
    name: Extract Blobs by ${{ github.actor }}
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    env:
      FDR: ${{ github.event.inputs.FIRMWARE_DUMP_REPO }}
      FDB: ${{ github.event.inputs.FIRMWARE_DUMP_BRANCH }}
      DTR: ${{ github.event.inputs.DEVICE_TREE_REPO }}
      DTB: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}
      DCN: ${{ github.event.inputs.DEVICE_CODENAME }}
      DVN: ${{ github.event.inputs.DEVICE_VENDORNAME }}
      UN: ${{ github.event.inputs.USER_NAME }}
      UEM: ${{ github.event.inputs.USER_EMAIL }}
      TR: android_vendor_${{ github.event.inputs.DEVICE_VENDORNAME }}_${{ github.event.inputs.DEVICE_CODENAME }}
    permissions:
      contents: write
    steps:
    - name: Cleanup storage
      uses: rokibhasansagar/slimhub_actions@main

    - name: Check Out
      uses: actions/checkout@v5

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12
        
    - name: Identity
      run: |
        git config --global user.name "${{ env.UN }}"
        git config --global user.email "${{ env.UEM }}"

    - name: Clone Device Tree
      run: |
        sudo apt update
        sudo apt install 7zip-standalone android-sdk-libsparse-utils erofs-utils neovim wireguard-tools -y
        mkdir workspace
        cd workspace
        git clone --depth=1 ${{ env.DTR }} -b ${{ env.DTB }} ./android/device/${{ env.DVN }}/${{ env.DCN }}

    - name: Clone LineageOS Tools and Utils
      run: |
        cd workspace
        git clone --depth=1 https://github.com/LineageOS/android_tools_extract-utils -b lineage-23.2 ./android/tools/extract-utils
        echo "Done cloning extract-utils."
        git clone --depth=1  https://github.com/LineageOS/android_prebuilts_extract-tools -b lineage-23.2 ./android/prebuilts/extract-tools
        echo "Done cloning extract-tools."

    - name: SSH
      env:
        WG_CONF: ${{ secrets.WG_CONF }}
        STUN_CONF: ${{ secrets.STUN_CONF }}
      run: |
        cp /etc/environment $GITHUB_WORKSPACE/environment.bak
        sudo sed -i '2,$d' /etc/environment
        mkdir ~/.ssh || true
        echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC4Oy2f1OTtbS1lIsxvrYkxSBM7PDK/IMrYZH23lXm59 u0_a314@localhost" >> ~/.ssh/authorized_keys
        echo $WG_CONF | base64 -d | unzstd > wg0.conf
        echo $STUN_CONF | base64 -d | unzstd > config.yaml
        aria2c https://github.com/tjjh89017/stunmesh-go/releases/download/v1.7.0/stunmesh-linux-amd64-v1.7.0 -o stunmesh-go
        chmod +x stunmesh-go
        sudo wg-quick up ./wg0.conf
        sudo ./stunmesh-go
        sudo cp $GITHUB_WORKSPACE/environment.bak /etc/environment
