name: Extract Blobs

on:
  workflow_dispatch:
    inputs:
      DEVICE_TREE_REPO:
        description: 'Device Tree Repository URL'
        required: true
        default: ''
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Repository Branch'
        required: true
        default: ''
      DEVICE_CODENAME:
        description: 'Device Codename'
        required: true
        default: ''
      DEVICE_VENDORNAME:
        description: 'Device Vendor Name'
        required: true
        default: ''
      USER_NAME:
        description: 'Name in Github Account'
        required: true
        default: 'Carlo Dee'
      USER_EMAIL:
        description: 'E-mail in Github Account'
        required: true
        default: 'carlodee.official@proton.me'

jobs:
  build:
    name: Extract Blobs by ${{ github.actor }}
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    env:
      FDR: ${{ github.event.inputs.FIRMWARE_DUMP_REPO }}
      FDB: ${{ github.event.inputs.FIRMWARE_DUMP_BRANCH }}
      DTR: ${{ github.event.inputs.DEVICE_TREE_REPO }}
      DTB: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}
      DCN: ${{ github.event.inputs.DEVICE_CODENAME }}
      DVN: ${{ github.event.inputs.DEVICE_VENDORNAME }}
      UN: ${{ github.event.inputs.USER_NAME }}
      UEM: ${{ github.event.inputs.USER_EMAIL }}
      TR: android_vendor_${{ github.event.inputs.DEVICE_VENDORNAME }}_${{ github.event.inputs.DEVICE_CODENAME }}
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v5

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12
        
    - name: Identity
      run: |
        git config --global user.name "${{ env.UN }}"
        git config --global user.email "${{ env.UEM }}"

    - name: Clone Device Tree
      run: |
        sudo apt update
        sudo apt install 7zip-standalone android-sdk-libsparse-utils erofs-utils -y
        mkdir workspace
        cd workspace
        git clone --depth=1 ${{ env.DTR }} -b ${{ env.DTB }} ./android/device/${{ env.DVN }}/${{ env.DCN }}

    - name: Clone LineageOS Tools and Utils
      run: |
        cd workspace
        git clone --depth=1 https://github.com/LineageOS/android_tools_extract-utils -b lineage-22.2 ./android/tools/extract-utils
        echo "Done cloning extract-utils."
        git clone --depth=1  https://github.com/LineageOS/android_prebuilts_extract-tools -b lineage-22.2 ./android/prebuilts/extract-tools
        echo "Done cloning extract-tools."

    - name: Setup upterm session
      uses: owenthereal/action-upterm@v1
      with:
        limit-access-to-actor: true
